config/routes.rb
Wws::Application.routes.draw do
  devise_for :users
  root 'home#index'

  namespace :admin do
    root 'index#index'

    resources :houses do
    	resources :house_wines, only: :index, as: :wines
    end

    resources :sales do
      resources :sale_wines, only: :index, as: :wines
    end

    resources :wines
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    user ||= User.new

    can :manage, :all
  end
end

app/models/house.rb
class House < ActiveRecord::Base

	has_many :wines
	has_many :sales

	def destroyable?
		true
	end
end

app/models/sale.rb
class Sale < ActiveRecord::Base

	belongs_to :house

	has_many :sale_wines
	has_many :wines, through: :sale_wines

  accepts_nested_attributes_for :sale_wines, :reject_if => :all_blank, :allow_destroy => true

	validates :house_id, presence: true

	def destroyable?
		true
	end
end

app/models/sale_wine.rb
class SaleWine < ActiveRecord::Base

	belongs_to :sale
	belongs_to :wine

	validates :sale_id, :wine_id, presence: true

	def destroyable?
		true
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wine.rb
class Wine < ActiveRecord::Base

	belongs_to :house

	has_many :sale_wines
	has_many :wines, through: :sale_wines

	validates :house_id, presence: true

	def destroyable?
		true
	end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'
end

app/controllers/admin/house_wines_controller.rb
#encoding: utf-8
class Admin::HouseWinesController < Admin::AdminController

  load_and_authorize_resource :house

  def index
  end

end

app/controllers/admin/houses_controller.rb
#encoding: utf-8
class Admin::HousesController < Admin::AdminController
  authorize_resource
  load_resource except: :create

  def index
  end

  def new
  end

  def create
    @house = House.new(house_params)
    if @house.save
      redirect_to edit_admin_house_url(@house), notice: t("flash_messages.house.create")
    else
      render :new
    end
  end

  def edit
    @house
  end

  def update
    if @house.update_attributes(house_params)
      redirect_to edit_admin_house_url(@house), notice: t("flash_messages.house.update")
    else
      render :edit
    end
  end

  def destroy
    @house.destroy if @house.destroyable?
    redirect_to admin_houses_url(), notice: t("flash_messages.house.destroy")
  end

  private

  def house_params
    params.require(:house).permit(:name, :country, :region, :city, :description, :website, :facebook_link)
  end
end

app/controllers/admin/index_controller.rb
class Admin::IndexController < Admin::AdminController
  def index
  end
end

app/controllers/admin/sale_wines_controller.rb
#encoding: utf-8
class Admin::SaleWinesController < Admin::AdminController

  load_and_authorize_resource :sale

  def index
    @sale = @sale.decorate
  end

end

app/controllers/admin/sales_controller.rb
#encoding: utf-8
class Admin::SalesController < Admin::AdminController
  authorize_resource
  load_resource except: :create

  def index
    @sales = @sales.decorate
  end

  def new
  end

  def create
    @sale = Sale.new(sale_params)
    if @sale.save
      redirect_to edit_admin_sale_url(@sale), notice: t("flash_messages.sale.create")
    else
      render :new
    end
  end

  def edit
    @sale = SaleDecorator.decorate(@sale)
  end

  def update
    if @sale.update_attributes(sale_params)
      redirect_to edit_admin_sale_url(@sale), notice: t("flash_messages.sale.update")
    else
      render :edit
    end
  end

  def destroy
    @sale.destroy if @sale.destroyable?
    redirect_to admin_sales_url(), notice: t("flash_messages.sale.destroy")
  end

  private

  def sale_params
    params.require(:sale).permit! #(:house_id, :begin_date, :end_date, :limit_for_validation, :limit_date, :sale_wines_attributes)
  end
end

app/controllers/admin/wines_controller.rb
#encoding: utf-8
class Admin::WinesController < Admin::AdminController
  authorize_resource
  load_resource except: :create
  load_and_authorize_resource :house, through: :wine, shallow: true

  def index
  end

  def new
  end

  def create
    @wine = Wine.new(wine_params)
    if @wine.save
      redirect_to edit_admin_wine_url(@wine), notice: t("flash_messages.wine.create")
    else
      render :new
    end
  end

  def edit
    @wine
  end

  def update
    if @wine.update_attributes(wine_params)
      redirect_to edit_admin_wine_url(@wine), notice: t("flash_messages.wine.update")
    else
      render :edit
    end
  end

  def destroy
    @wine.destroy if @wine.destroyable?
    redirect_to admin_wines_url(), notice: t("flash_messages.wine.destroy")
  end

  private

  def wine_params
    params.require(:wine).permit(:name, :designation, :vintage, :variety, :description, :house_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/house_wines/index.html.slim
- content_for :header_title do
  = t("house.title.edit", house: @house.name)

- content_for :breadcrumb do
  ul.breadcrumb
    li.first
      = link_to "Admin", admin_root_path()
      span.divider >
    li
      = link_to "Maisons", admin_houses_path()
      span.divider >
    li.active Editer

= render "admin/houses/menu", selected: :wines, house: @house

- content_for :page_title do
  = t("house.title.edit", house: @house.name)

table class="table table-striped table-condensed"
  thead
    tr
      th
        = Wine.human_attribute_name(:name).humanize
      th
        = Wine.human_attribute_name(:designation).humanize
      th
        = Wine.human_attribute_name(:vintage).humanize
      th
        = Wine.human_attribute_name(:variety).humanize
      th
        = Wine.human_attribute_name(:house_id).humanize
  tbody
    - if @house.wines.any?
      - @house.wines.each do |wine|
        tr
          td = link_to wine.name, edit_admin_wine_path(wine)
          td = wine.designation
          td = wine.vintage
          td = wine.variety
          td = wine.house.name
    - else
      tr
        td colspan="5"
          = t("no_db_results")

app/views/admin/houses/_form.html.slim
= simple_form_for [:admin, house], html: { class: 'form-horizontal' } do |f|
  = f.input :name
  = f.input :country
  = f.input :region
  = f.input :city
  = f.input :description
  = f.input :website
  = f.input :facebook_link

  .form-actions
    = f.submit 'Enregistrer', class: "btn btn-success"

app/views/admin/houses/_house.html.slim
tr
  td = link_to house.name, edit_admin_house_path(house)
  td = house.country
  td = house.region
  td = house.city
  td
    - if can? :destroy, house
      = link_to admin_house_path(house), method: :delete, class: "btn" do
        i.icon-trash
    - else
      | &nbsp;

app/views/admin/houses/_menu.html.slim
ul class= ['nav', 'nav-tabs']
  li class= ((selected == :house)   ? "active" : nil ) = link_to("Maison",	edit_admin_house_path(house))
  li class= ((selected == :wines)   ? "active" : nil ) = link_to("Vins",		admin_house_wines_path(house))
 

app/views/admin/houses/edit.html.slim
- content_for :header_title do
  = t("house.title.edit", house: @house.name)

- content_for :breadcrumb do
  ul.breadcrumb
    li.first 
      = link_to "Admin", admin_root_path() 
      span.divider >
    li 
      = link_to "Maisons", admin_houses_path()
      span.divider >
    li.active Editer

= render "menu", selected: :house, house: @house    

- content_for :page_title do
  = t("house.title.edit", house: @house.name)

= render "form", house: @house

app/views/admin/houses/index.html.slim
- content_for :header_title do
  = t("house.title.index")

- content_for :breadcrumb do
  ul.breadcrumb
    li.first 
      = link_to "Admin", admin_root_path() 
      span.divider >
    li Maisons

- content_for :page_title do
  = t("house.title.index")

a= link_to "Créer une maison", new_admin_house_path

table class="table table-striped table-condensed"
  thead
    tr
      th
        = House.human_attribute_name(:name).humanize
      th
        = House.human_attribute_name(:country).humanize
      th
        = House.human_attribute_name(:region).humanize
      th
        = House.human_attribute_name(:city).humanize
      th
        = t("actions")
  tbody
    - if @houses.any?
      = render @houses
    - else
      tr
        td colspan="5"
          = t("no_db_results")

app/views/admin/houses/new.html.slim
- content_for :header_title do
  = t("house.title.new")

- content_for :breadcrumb do
  ul.breadcrumb
    li.first 
      = link_to "Admin", admin_root_path() 
      span.divider >
    li 
      = link_to "Maisons", admin_houses_path()
      span.divider >
    li.active Créer  

- content_for :page_title do
  = t("house.title.new")

= render "form", house: @house

app/views/admin/houses/wines/index.html.slim
- content_for :header_title do
  = t("house.title.edit", house: @house.name)

- content_for :breadcrumb do
  ul.breadcrumb
    li.first 
      = link_to "Admin", admin_root_path() 
      span.divider >
    li 
      = link_to "Maisons", admin_houses_path()
      span.divider >
    li.active Editer

= render "admin/houses/menu", selected: :wines, house: @house    

- content_for :page_title do
  = t("house.title.edit", house: @house.name)

table class="table table-striped table-condensed"
  thead
    tr
      th
        = Wine.human_attribute_name(:name).humanize
      th
        = Wine.human_attribute_name(:designation).humanize
      th
        = Wine.human_attribute_name(:vintage).humanize
      th
        = Wine.human_attribute_name(:variety).humanize
      th
        = Wine.human_attribute_name(:house_id).humanize  
  tbody
    - if @house.wines.any?
      - @house.wines.each do |wine|
        tr
          td = link_to wine.name, edit_admin_wine_path(wine)
          td = wine.designation
          td = wine.vintage
          td = wine.variety
          td = wine.house.name
    - else
      tr
        td colspan="5"
          = t("no_db_results")

app/views/admin/index/index.html.slim
h1 admin

app/views/admin/sale_wines/_sale_wine_fields.html.slim
tr.nested-fields
  td.left= f.association :wine, label: false
  td.center= link_to_remove_association f, class: "btn" do
    i.icon-trash.icon-large

app/views/admin/sale_wines/index.html.slim
- content_for :header_title do
  = t("sale.title.edit", sale: @sale.name)

- content_for :breadcrumb do
  ul.breadcrumb
    li.first
      = link_to "Admin", admin_root_path()
      span.divider >
    li
      = link_to "Ventes", admin_sales_path()
      span.divider >
    li.active Editer

= render "admin/sales/menu", selected: :wines, sale: @sale

- content_for :page_title do
  = t("sale.title.edit", sale: @sale.name)

#sale-wines
  = simple_form_for [:admin, @sale], html: { class: 'form-horizontal' } do |f|
    table
      thead
        tr
          th.left width="70%" Vin
          th.center width="30%" Actions

      tbody#tbody
        = f.simple_fields_for :sale_wines do |sale_wine|
          = render 'sale_wine_fields', f: sale_wine, render_options: { wrapper: 'bootstrap' }

    .links
      = link_to_add_association f, :sale_wines , partial: "sale_wine_fields", data: { "association-insertion-node" => "#tbody", "association-insertion-method" => "append" }, class: "btn", render_options: {:wrapper => 'bootstrap' } do
        i.icon-plus-sign.icon-large
        | Ajouter un vin

    = f.submit

app/views/admin/wines/_form.html.slim
= simple_form_for [:admin, wine], html: { class: 'form-horizontal' } do |f|
  = f.input :name
  = f.input :designation
  = f.input :vintage
  = f.input :variety
  = f.input :description
  = f.association :house

  .form-actions
    = f.submit 'Enregistrer', class: "btn btn-success"

app/views/admin/wines/edit.html.slim
- content_for :header_title do
  = t("wine.title.edit", wine: @wine.name)

- content_for :breadcrumb do
  ul.breadcrumb
    li.first 
      = link_to "Admin", admin_root_path() 
      span.divider >
    li 
      = link_to "Vins", admin_wines_path()
      span.divider >
    li.active Editer  

- content_for :page_title do
  = t("wine.title.edit", wine: @wine.name)  

= render "form", wine: @wine

app/views/admin/wines/index.html.slim
- content_for :header_title do
  = t("wine.title.index")

- content_for :breadcrumb do
  ul.breadcrumb
    li.first 
      = link_to "Admin", admin_root_path() 
      span.divider >
    li Vins

- content_for :page_title do
  = t("wine.title.index")      

a= link_to "Créer un vin", new_admin_wine_path

table class="table table-striped table-condensed"
  thead
    tr
      th
        = Wine.human_attribute_name(:name).humanize
      th
        = Wine.human_attribute_name(:designation).humanize
      th
        = Wine.human_attribute_name(:vintage).humanize
      th
        = Wine.human_attribute_name(:variety).humanize
      th
        = Wine.human_attribute_name(:house_id).humanize  
      th
        = t("actions")
  tbody
    - if @wines.any?
      = render @wines
    - else
      tr
        td colspan="6"
          = t("no_db_results")

app/views/admin/wines/new.html.slim
- content_for :header_title do
  = t("wine.title.new")

- content_for :breadcrumb do
  ul.breadcrumb
    li.first 
      = link_to "Admin", admin_root_path() 
      span.divider >
    li 
      = link_to "Vins", admin_wines_path()
      span.divider >
    li.active Créer  

- content_for :page_title do
  = t("wine.title.new")      

= render "form", wine: @wine

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/layouts/admin.html.slim
- content_for :menu do
  = render 'navigations/admin_menu'

= render template: 'layouts/main'

app/views/layouts/application.html.slim
doctype html
html
  head
  meta name="viewport" content="width=device-width" initial-scale="1.0"
    title
      = yield :header_title
      |  | #{ t("wws")}

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

    script type="text/javascript"
      | var ready = function(){
      |   new Wws.Views.SharedView();
      = yield :javascripts if content_for? :javascripts
      | };
      | $(document).on("page:load", ready);
      | $(document).ready(ready);

  body
    .root
      header
        .logo

        .user-action
      
      .menu
        = render "navigations/main_menu"

      .content
        = yield

      .facebook
        h1 FACEBOOK

app/views/layouts/main.html.slim
doctype html
html
  head
  meta name="viewport" content="width=device-width" initial-scale="1.0"
    title
      = yield :header_title
      |  | #{ t("wws")}

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

    script type="text/javascript"
      | var ready = function(){
      |   new Wws.Views.AdminView();
      = yield :javascripts if content_for? :javascripts
      | };
      | $(document).on("page:load", ready);
      | $(document).ready(ready);

  body
    .root
      header
        .logo

        .user-action
      
      .menu
        = yield :menu if content_for? :menu

      .content
        = yield :breadcrumb if content_for? :breadcrumb

        - if content_for? :page_title
          h1 = yield :page_title

        = render "/shared/alerts", flash_messages: flash
        
        = yield

      .facebook
        h1 FACEBOOK

app/views/navigations/_admin_menu.html.slim
ul.nav.nav-tabs.nav-stacked
  li= link_to t("wws"), root_path()
  li 
    = link_to "Maisons", admin_houses_path
  li 
    = link_to "Ventes", admin_sales_path  
  li 
    = link_to "Vins", admin_wines_path

app/views/navigations/_main_menu.html.slim
ul.nav.nav-tabs.nav-stacked
  li= link_to t("wws"), root_path()
  li 
    a href="#" Item 1
  li 
    a href="#" Item 2
  li 
    a href="#" Item 3
  li 
    a href="#" Item 4

app/views/shared/_alerts.html.slim
- if flash_messages.any?
  - flash_messages.each do |type, message|
    div.alert*{class: "alert-#{type}"} = message

app/views/shared/_errors.html.slim
- if object.try(:errors).try(:any?)
  section.error-box
    header
      h2 Il y a des erreurs dans ce formulaire !
    section.content
      ul
        - object.errors.full_messages.each do |error|
          li= error